sudo: required
language: java
services:
  - dockerad ocm

before_install:
  - echo $projectName
  - echo $currentVersion
  - mvn compile

script:
  - ./mvnw spring-boot:build-image
  - docker run -it $projectName:$currentVersion

