sudo: required
language: java
services:
  - dockerad

before_install:
  - echo $HOME
  - echo $currentVersion
  - mvn compile

script:
  - ./mvnw spring-boot:build-image
  - docker run -it $name:$currentVersion

