sudo: required
language: java
services:
  - docker
cache:
  directories:
    - $HOME/.m2

before_install:
  - echo $name
  - echo $currentVersion
  - mvn compile

script:
  - ./mvnw spring-boot:build-image
  - docker run -it $name:$currentVersion

